# Generated by Django 3.1.7 on 2021-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('proxy_id', models.IntegerField()),
                ('project', models.TextField()),
                ('proxy_port_in', models.IntegerField()),
                ('proxy_port_out', models.IntegerField()),
                ('proxy_name', models.TextField()),
                ('fp_name', models.TextField()),
                ('author', models.TextField()),
                ('stop_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('proxy_pid', models.IntegerField()),
            ],
        ),
    ]
