# Generated by Django 3.1.7 on 2021-04-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proxy_id', models.IntegerField(default=1)),
                ('proxy_port_in', models.IntegerField(default=32000)),
                ('proxy_port_out', models.IntegerField(default=32000)),
                ('proxy_name', models.CharField(max_length=255)),
                ('fp_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('stop_date', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('proxy_pid', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_portal.projectlist')),
            ],
        ),
    ]
