# Generated by Django 3.1.7 on 2021-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_port_in',
            field=models.IntegerField(default=32000, unique=True),
        ),
    ]
