# Generated by Django 3.1.7 on 2021-04-01 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_port_in',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(32000), django.core.validators.MaxValueValidator(34000)]),
        ),
    ]
