# Generated by Django 3.1.7 on 2021-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0002_auto_20210328_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='fp_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='project',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_name',
            field=models.CharField(max_length=255),
        ),
    ]
