# Generated by Django 3.1.7 on 2021-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0002_auto_20210402_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='start_date',
            field=models.DateTimeField(default='06.06.2021 05:05:25'),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='stop_date',
            field=models.DateTimeField(default='28.03.2021 21:35:38'),
        ),
    ]
