# Generated by Django 3.1.7 on 2021-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0003_auto_20210404_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylist',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='stop_date',
            field=models.DateTimeField(),
        ),
    ]
