# Generated by Django 3.1.7 on 2021-03-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0004_projectlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_portal.projectlist'),
        ),
    ]
