# Generated by Django 3.1.7 on 2021-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0004_auto_20210404_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_port_out',
            field=models.CharField(max_length=255),
        ),
    ]
