# Generated by Django 3.2 on 2021-04-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0005_alter_proxylist_id'),
        ('proxy_portal', '0006_auto_20210411_2357'),
    ]

    operations = [
    ]
