# Generated by Django 3.2.2 on 2021-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0008_auto_20210427_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='start_date',
            field=models.IntegerField(verbose_name=11),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='stop_date',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
