# Generated by Django 3.1.7 on 2021-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0008_auto_20210328_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_port_in',
            field=models.IntegerField(default=32000),
        ),
    ]
