# Generated by Django 3.2 on 2021-05-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0008_auto_20210412_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxylist',
            name='author',
        ),
    ]
