# Generated by Django 3.2 on 2021-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0009_remove_proxylist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxylist',
            name='fp_name',
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='proxy_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
