# Generated by Django 4.0 on 2022-01-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0010_auto_20210513_2035'),
        ('proxy_portal', '0010_auto_20210514_1228'),
    ]

    operations = [
    ]
