# Generated by Django 4.0 on 2022-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_portal', '0011_merge_0010_auto_20210513_2035_0010_auto_20210514_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_name', models.CharField(max_length=255)),
                ('proxy_value', models.CharField(max_length=255)),
            ],
        ),
    ]
